In [7]:
import tensorflow as tf
import numpy as np

In [6]:
tf.__version__

'2.0.0'

#### Creating Tensors

In [10]:
string = tf.Variable("string character", tf.string)
number = tf.Variable(100, tf.int16)
float_character = tf.Variable(1.345, tf.float64)

#### Rank of a Tensor

* Way to determing the rank is deepest level of nested lists

In [27]:
string_array = tf.Variable(['string_1', 'string_2', 'string_3'], tf.string)
# rank of the above array is only 1
print('Rank of string_array is : ', tf.rank(string_array))
print()

string_array_1 = tf.Variable([['string_1', 'string_2', 'string_3'], 
                              ['string_1', 'string_2', 'string_3']], tf.string)
# rank of the above array is 2, since we have two lists inside a list
print('Rank of string_array_1 is : ', tf.rank(string_array_1))


Rank of string_array is :  tf.Tensor(1, shape=(), dtype=int32)

Rank of string_array_1 is :  tf.Tensor(2, shape=(), dtype=int32)


#### Shape of a Tensor

* This tells us, how many items we have in each dimension

In [28]:
print("Shape of string_array is: ", string_array.shape)
print()
print("Shape of string_array_1 is: ", string_array_1.shape)


Shape of string_array is:  (3,)

Shape of string_array_1 is:  (2, 3)


#### Changing the shape

In [34]:
tensor_1 = tf.ones(shape = [1,2,3])
print('tensor_1 : ', tensor_1)
print()
print('Shape of the tensor: ', tensor_1.shape)
print()
print('Rank of the tensor: ', tf.rank(tensor_1))

tensor_1 :  tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)

Shape of the tensor:  (1, 2, 3)

Rank of the tensor:  tf.Tensor(3, shape=(), dtype=int32)


* flatten the tensor with shape = [-1]

In [38]:
tensor_2 = tf.reshape(tensor = tensor_1,
                      shape = [-1])
print('tensor_2 : ', tensor_2)
print()
print('Shape of the tensor_2: ', tensor_2.shape)
print()
print('Rank of the tensor_2: ', tf.rank(tensor_2))

tensor_2 :  tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)

Shape of the tensor_2:  (6,)

Rank of the tensor_2:  tf.Tensor(1, shape=(), dtype=int32)


* Here the rule is such that the multiplication of all elements of the shape should be equal to the total number of elements in the tensor

In [41]:
tensor_3 = tf.reshape(tensor = tensor_1,
                      shape = [2,1,3])
print('tensor_3 : ', tensor_3)
print()
print('Shape of the tensor_3: ', tensor_3.shape)
print()
print('Rank of the tensor_3: ', tf.rank(tensor_3))

tensor_3 :  tf.Tensor(
[[[1. 1. 1.]]

 [[1. 1. 1.]]], shape=(2, 1, 3), dtype=float32)

Shape of the tensor_3:  (2, 1, 3)

Rank of the tensor_3:  tf.Tensor(3, shape=(), dtype=int32)


In [42]:
tensor_4 = tf.reshape(tensor = tensor_1,
                      shape = [3,2,1])
print('tensor_4 : ', tensor_4)
print()
print('Shape of the tensor_4: ', tensor_4.shape)
print()
print('Rank of the tensor_4: ', tf.rank(tensor_4))

tensor_4 :  tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)

Shape of the tensor_4:  (3, 2, 1)

Rank of the tensor_4:  tf.Tensor(3, shape=(), dtype=int32)


* if shape = [3,-1,1], here -1 tells the tensor to calculate the size of the dimension in that place

In [43]:
tensor_5 = tf.reshape(tensor = tensor_1,
                      shape = [3,-1,1])
print('tensor_5 : ', tensor_4)
print()
print('Shape of the tensor_5: ', tensor_5.shape)
print()
print('Rank of the tensor_5: ', tf.rank(tensor_5))

tensor_5 :  tf.Tensor(
[[[1.]
  [1.]]

 [[1.]
  [1.]]

 [[1.]
  [1.]]], shape=(3, 2, 1), dtype=float32)

Shape of the tensor_5:  (3, 2, 1)

Rank of the tensor_5:  tf.Tensor(3, shape=(), dtype=int32)


#### Evaluate a Tensor

Evaluation of tensor in other words is to get its value. Since tensors represent a partially complete computation we will sometimes need to run what's called a 'session' to evaluate the tensor.

In [56]:
tf.get_static_value(tensor_1)

array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [57]:
tf.keras.backend.eval(tensor_1)

array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)